<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>36a10222-b406-4282-a07d-f7f776af213f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='privateEvents']/div/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2f93230-7f9e-4796-8103-48f527f8222b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testing.aljomaihfamilyapp.com/admin/birthNews/addParents</value>
      <webElementGuid>9ef4275c-b515-4c64-8f94-61d1959a3571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#imageModal</value>
      <webElementGuid>a2a205e4-c60d-4fc3-9a08-95c93a5ce679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>435a59a8-c602-481a-89cf-695f8e530ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>17b381d9-aadd-40f6-a876-02f10970b61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إنشاء خبر مواليد</value>
      <webElementGuid>0ecd05c7-4fac-465e-88b1-ca77851eaed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privateEvents&quot;)/div[@class=&quot;grid simple vertical mobile-scroll&quot;]/div[@class=&quot;grid-body no-border&quot;]/div[@class=&quot;row control&quot;]/div[@class=&quot;col-sm-3 col-xs-12&quot;]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>eb7257dc-72d4-4d72-9af0-a1e98e97e966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Daleel</value>
      <webElementGuid>1c00b7c8-e7a4-4544-8e9c-5d0ebb5a5ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='privateEvents']/div/div/div/div[3]/a</value>
      <webElementGuid>7626c739-0e10-4183-906b-d245dff770c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إنشاء خبر مواليد')]</value>
      <webElementGuid>328460eb-7d85-4d9c-802c-31db45341450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أخبار المواليد'])[1]/following::a[1]</value>
      <webElementGuid>3411281d-6c21-44dc-85a3-397fc0b34fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حذف'])[1]/following::a[1]</value>
      <webElementGuid>8bb65ee3-997e-4cd0-a086-61d5afc4be2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/preceding::a[1]</value>
      <webElementGuid>4a97ec9c-4be1-49c4-b8f8-171949b4655d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاستمارة'])[1]/preceding::a[1]</value>
      <webElementGuid>5e45c890-9eea-419c-8e1a-1489bd4aa6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إنشاء خبر مواليد']/parent::*</value>
      <webElementGuid>d3e348c2-150f-4734-91b8-627f86d9f095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testing.aljomaihfamilyapp.com/admin/birthNews/addParents')]</value>
      <webElementGuid>d520ee04-a0d6-4895-a139-ef7e75eee5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>3dad5e64-2ee9-4609-a6ad-6b7e69673202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testing.aljomaihfamilyapp.com/admin/birthNews/addParents' and (text() = 'إنشاء خبر مواليد' or . = 'إنشاء خبر مواليد')]</value>
      <webElementGuid>d5c01b24-884d-4993-a7c4-5bf9d05258d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إضافة خبر')]</value>
      <webElementGuid>1b330914-aa6d-408b-ba52-10c5eed5a3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الأخبار العامة'])[2]/following::a[1]</value>
      <webElementGuid>7e4c7678-7eb9-4a98-9467-51b6a34802f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عنوان الخبر'])[1]/preceding::a[1]</value>
      <webElementGuid>30ecd6d0-dbb3-4484-9a75-212fde2d65b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الصور'])[1]/preceding::a[1]</value>
      <webElementGuid>f17156d0-1163-433e-87ed-205da0e85105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة خبر']/parent::*</value>
      <webElementGuid>613bfc5c-f0eb-421b-ab94-9b1f54002aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testing.aljomaihfamilyapp.com/admin/news/create?type=general')]</value>
      <webElementGuid>ece8cb01-744b-4a16-994e-cc6a3371011b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testing.aljomaihfamilyapp.com/admin/news/create?type=general' and (text() = 'إضافة خبر' or . = 'إضافة خبر')]</value>
      <webElementGuid>2723e213-d92e-4df2-808c-db286005ccd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bar-inner']/ul/li[3]/a</value>
      <webElementGuid>565502ea-74c3-4e2e-9498-dd936720da94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هام'])[1]/following::a[1]</value>
      <webElementGuid>a60ccb2d-d436-431a-87a9-7cdeaa66e03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصويت'])[1]/following::a[2]</value>
      <webElementGuid>7894ca5f-515e-4eda-9c1a-5facb7a9df04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>be631931-d001-4a01-9625-ea1c1a1cb082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>b1a5d6f7-b49b-444f-91d4-664b1be6bcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Daleel' and @href = '#' and (text() = ' المكتبة* ' or . = ' المكتبة* ')]</value>
      <webElementGuid>95ede2b1-142c-4039-8675-e6bdc7966adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إضافة')]</value>
      <webElementGuid>04484a21-ab93-4d47-80d3-60144bc8e6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المراجع'])[1]/following::a[2]</value>
      <webElementGuid>c4753ee4-4b56-44dc-b9ed-1137513b3270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المرجع'])[1]/preceding::a[1]</value>
      <webElementGuid>3db25aa7-40cc-4bca-b741-966072853539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المراجع المراجع المراجع ٢'])[1]/preceding::a[1]</value>
      <webElementGuid>cd6e3489-31df-4c65-b873-cd8e7af4f7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة']/parent::*</value>
      <webElementGuid>1198d952-4475-49bb-ac11-580d0543226e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>0f962e53-8478-4357-b0c8-6e5986e2753a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>55a65291-0d44-4043-8652-83014f1ffb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'إضافة' or . = 'إضافة')]</value>
      <webElementGuid>3cf70ab3-49fc-4c2a-8f6f-689a9819e66b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
