<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>91675223-aaea-4231-a7a7-16ee21803e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonMotherFamily']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonMotherFamily</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14d8d918-e15a-4a0a-abdc-05c5adf6c625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06e71484-b157-4477-a9e7-260e2bf123cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg open-model-btn-mother</value>
      <webElementGuid>e9e7ae88-1a79-412d-ab4d-655c7d622f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonMotherFamily</value>
      <webElementGuid>049af239-2251-493c-9678-40a0001a0745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>buttonMotherFamilyFun()</value>
      <webElementGuid>e08b19c5-b039-40c6-878f-7212ebe2c3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الام من الاسرة</value>
      <webElementGuid>ecd74108-0884-45c0-aef0-f769dfcc3c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonMotherFamily&quot;)</value>
      <webElementGuid>4ff90d79-2200-4ae7-94f5-58cb46945dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonMotherFamily']</value>
      <webElementGuid>7a1b6d53-28f4-4428-8a30-1f0a5c427c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ParentForm']/div[6]/div/button[4]</value>
      <webElementGuid>4dad7901-449e-4fce-87a8-5709a51a5a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاب من خارج الاسرة'])[1]/following::button[1]</value>
      <webElementGuid>ad001082-1ed1-493b-b261-adce1d1478ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاب من الاسرة'])[1]/following::button[2]</value>
      <webElementGuid>b3c9e8dc-887d-47ac-ab00-7dc2ca1e3944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الام من خارج الاسرة'])[1]/preceding::button[1]</value>
      <webElementGuid>5b3d5799-7c15-476c-bc39-00b655943b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إلغاء'])[1]/preceding::button[2]</value>
      <webElementGuid>03709fad-63a7-47bc-84b6-203bf7f59e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الام من الاسرة']/parent::*</value>
      <webElementGuid>3b3a87e7-02ec-4882-9644-c44da5e15689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>40059717-11d6-422f-a693-a80f4f6892ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'buttonMotherFamily' and (text() = 'الام من الاسرة' or . = 'الام من الاسرة')]</value>
      <webElementGuid>00479c82-7c69-412e-a9ba-31f8c6558fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonFatherFamily']</value>
      <webElementGuid>54c10968-3246-43af-a427-7f8fa0bd5040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ParentForm']/div[6]/div/button[2]</value>
      <webElementGuid>cba2fc74-5cb1-4338-a911-dad052a9a054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر الاب او الام من دليل الاسرة'])[1]/following::button[1]</value>
      <webElementGuid>6de64ba6-9fac-4e50-a0f6-d292d3e2a478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أمل'])[1]/following::button[2]</value>
      <webElementGuid>b38c2388-71cc-457a-a50c-c5c19d4200cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاب من خارج الاسرة'])[1]/preceding::button[1]</value>
      <webElementGuid>ba50cca7-dc96-410c-b0fe-13de53665c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الام من الاسرة'])[1]/preceding::button[2]</value>
      <webElementGuid>1c583988-99d6-4e71-89fe-177089a4cf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الاب من الاسرة']/parent::*</value>
      <webElementGuid>8e07a385-684e-430b-a255-795c8cd30007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6f4066b1-45d9-45dc-abfe-0edf774ebcd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'buttonFatherFamily' and (text() = 'الاب من الاسرة' or . = 'الاب من الاسرة')]</value>
      <webElementGuid>d69a1500-4d88-4a68-b7d5-1a8453f97c6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
