<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_superadmin_image-logo</name>
   <tag></tag>
   <elementGuidId>a098b1d8-7ca3-430d-82f8-1c0b18cb7709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a > img.image-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd4280f5-60c1-4734-acc0-bcd941439265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-logo</value>
      <webElementGuid>395fd619-da2a-4966-9dfe-87262474b8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png</value>
      <webElementGuid>06895208-2e9c-4410-9c7e-534aadd382f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3e6900af-73f8-48d1-aa35-fcddf13e9b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;rtl horizontal-menu   breakpoint-1024 pace-done&quot;]/div[@class=&quot;header navbar navbar-inverse&quot;]/div[@class=&quot;navbar-inner&quot;]/div[@class=&quot;row logo&quot;]/div[@class=&quot;header-section&quot;]/div[@class=&quot;col-md-4 text-center&quot;]/a[1]/img[@class=&quot;image-logo&quot;]</value>
      <webElementGuid>714fa5de-7e6e-4ccc-ab60-e1c6bab655a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png')]</value>
      <webElementGuid>2721e3d7-ed66-411a-a7ac-5c6cdcf03d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>cae878cf-4fd6-4b8d-84c9-41f31902d546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png']</value>
      <webElementGuid>9c543d55-ea91-41ea-bf35-a82ff6dee96b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
