<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn-submit_1</name>
   <tag></tag>
   <elementGuidId>bcab1ba3-7b4e-43d0-8afd-322d1240c8cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='btn-submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-footer > #btn-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>361ce004-262c-4d95-8822-fcdcf124c4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-cons</value>
      <webElementGuid>3f967f71-17c6-4b12-94db-8df77c458fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-submit</value>
      <webElementGuid>e2407637-258b-4bf6-8201-55f47cf5752a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5cb53dad-6ff0-46da-a87d-40b5c75df428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>حفظ</value>
      <webElementGuid>bff2b9ad-ea74-46b8-9e3e-ad54444aebf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_news-attachments&quot;)/div[@class=&quot;modal-footer&quot;]/input[@id=&quot;btn-submit&quot;]</value>
      <webElementGuid>da377d87-d9df-4e84-8827-9f10a36ed6cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='btn-submit'])[3]</value>
      <webElementGuid>69590969-0c54-44b9-ba89-512dfc56be31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_news-attachments']/div[2]/input</value>
      <webElementGuid>155cf856-373d-490f-9a73-16648435adb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/form/div[2]/input</value>
      <webElementGuid>c3cc2f45-de89-4ea1-91a2-99207e4378b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btn-submit' and @type = 'submit']</value>
      <webElementGuid>71542709-6ad1-4c2c-85b9-7e81b3b54b69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
