<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__locations3298037title</name>
   <tag></tag>
   <elementGuidId>eb7fede0-2190-43a0-9d54-433fb3f36c1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='locations[3298037][title]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;locations[3298037][title]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7e26cc1-f887-41ec-afb8-448ff190b76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>29276a30-ab6a-43c0-b589-2c2d71ea8036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>989c072d-d04a-4fa9-a91f-9cba96fe9b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>locations[3298037][title]</value>
      <webElementGuid>de635dcb-bffd-4b1e-b505-a814b5e70de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad474e3a-ac6f-4b37-89a6-eaaa8487efae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location_3298037&quot;)/div[@class=&quot;grid-body&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-6 col-sm-12&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7e732158-a3cf-43ce-a2fc-124a778658ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='locations[3298037][title]']</value>
      <webElementGuid>c6446507-a566-42f3-a277-54c5370ec9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location_3298037']/div[2]/div/div[3]/input</value>
      <webElementGuid>a7507ee0-446f-4dd5-9806-c8f93490c2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4dd61696-241f-421f-8002-7ac4dd78463b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'locations[3298037][title]' and @type = 'text']</value>
      <webElementGuid>5cce9387-2e25-411f-b3ac-c6a1e5a8e726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
