<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btn-submit_1_2</name>
   <tag></tag>
   <elementGuidId>fe39c7aa-1025-4a71-96b4-159d565c43b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7366b08a-20d4-4bc0-91e3-d5a66b70c8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-cons</value>
      <webElementGuid>e305605d-0b5a-4acb-877a-9192452c8bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-submit</value>
      <webElementGuid>e19fa1cd-b702-461c-83c7-0659338d0146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$(&quot;#form_news&quot;).trigger(&quot;submit&quot;);</value>
      <webElementGuid>dda633a4-e67d-401f-8686-4d8322d87175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>810492f2-b5b9-4486-b549-b18e438943fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>التالى</value>
      <webElementGuid>dc2c8768-18a0-46af-9a30-5f0a0166bb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;rtl horizontal-menu   breakpoint-1024 pace-done&quot;]/div[@class=&quot;page-container row-fluid&quot;]/div[@class=&quot;page-content m-0&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;content-section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;grid simple&quot;]/div[@class=&quot;grid-body&quot;]/div[@class=&quot;form-actions&quot;]/div[@class=&quot;pull-right&quot;]/input[@id=&quot;btn-submit&quot;]</value>
      <webElementGuid>9e2b41db-b3fd-40b5-a8ec-dd768693d838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn-submit']</value>
      <webElementGuid>9be7ddf6-3def-4807-9e48-6f7136ca6038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d0bafb7-4986-4c96-8249-9fe5588ec82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btn-submit' and @type = 'submit']</value>
      <webElementGuid>6c6dbf36-a983-45b4-a58e-8274da0748b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
