<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__baby_name</name>
   <tag></tag>
   <elementGuidId>5f002b60-f982-40f8-bc17-7cf6e4dad213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1stBabyText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1stBabyText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>142e78b6-d2c2-47a2-93de-1fa11ee0b31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1stBabyText</value>
      <webElementGuid>791cd2e2-50c8-4d46-95a8-4d422138b762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control father_mother_text</value>
      <webElementGuid>12fba536-738e-4dae-81e4-8fc7cf3eba36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الإسم الأول</value>
      <webElementGuid>289aab2e-3527-4448-9b45-d52e50dacd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>95974b8f-4835-4baa-97ed-f01322668bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>baby_name[]</value>
      <webElementGuid>af4ec5f8-2abb-429b-834e-c145edba66ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef7040e4-8c63-4200-b21c-50948e476cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1stBabyText&quot;)</value>
      <webElementGuid>0f87fb89-5b6f-441c-aa84-ab7403dff36e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1stBabyText']</value>
      <webElementGuid>aeeb9a80-010a-4e6f-9ebd-a0965e9dda5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='BabyForm']/div[6]/div[2]/div/div/div[3]/input</value>
      <webElementGuid>78b76473-3c3c-4728-b071-f7e1bd2e4350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ca1d2cb2-b630-4f6d-a625-c5166be43d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '1stBabyText' and @placeholder = 'الإسم الأول' and @name = 'baby_name[]' and @type = 'text']</value>
      <webElementGuid>e8eb2933-0c71-4496-8482-fc3332977b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
