<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__content_description4726828description</name>
   <tag></tag>
   <elementGuidId>00d4ebd0-9b34-4908-9571-5955a56b0c31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='content_description_4726828']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content_description_4726828</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dddcfd5a-b319-4234-851a-100144bf694c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control f-s-15 content-description</value>
      <webElementGuid>e6bb4e1c-5920-45b6-b178-5129b239fd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4a9a2fe3-592c-41c9-a387-38d662fa59ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-count</name>
      <type>Main</type>
      <value>4726828</value>
      <webElementGuid>8617d0de-da56-4c69-b458-b6317f595906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content_description_4726828</value>
      <webElementGuid>a40bfd9b-3d10-4651-9ac0-ffb1dd35c0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content_description[4726828][description]</value>
      <webElementGuid>cd0be9ec-52a0-4c05-b50a-900d082c78d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0e27cf70-7aaa-4249-bdad-565f2c33a060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_description_4726828&quot;)</value>
      <webElementGuid>65b1fbcf-979d-40f1-82a5-0c10050b3b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='content_description_4726828']</value>
      <webElementGuid>b96f5306-6b0a-43de-80c5-c6c903ecb2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4726828']/div/div/textarea</value>
      <webElementGuid>aa84a062-5b98-45c2-b549-2dbb298c2a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4e32ee8d-a596-4b9b-979f-2c6379312ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'content_description_4726828' and @name = 'content_description[4726828][description]']</value>
      <webElementGuid>11e1e205-eca4-4adf-9ac6-5f8f7e5106ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
