<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__locations3298037description</name>
   <tag></tag>
   <elementGuidId>c283d7cc-e474-443a-a449-5b04f509b23c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='location_description_3298037']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location_description_3298037</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eac8b3e7-b44b-41b0-a211-085ad7aa7a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>79ea4016-3581-420d-839f-c00889bfa45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location_description_3298037</value>
      <webElementGuid>8d7166e5-f074-4377-90d5-78f0b3cbabc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bbb1c74c-4064-46cd-b38b-4923a195b4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>locations[3298037][description]</value>
      <webElementGuid>1a3e3178-e6d2-4a4d-a426-da5fccc901a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3fb22631-d56b-4be6-87d5-29440ee08868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location_description_3298037&quot;)</value>
      <webElementGuid>cc6d0719-db8b-48fb-8d83-be92dc8d8ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='location_description_3298037']</value>
      <webElementGuid>ef58ed27-826b-47c2-b56e-44c25837841c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='location_3298037']/div[2]/div/div[2]/textarea</value>
      <webElementGuid>4c8369b7-dace-41f3-9bcc-247400905c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/textarea</value>
      <webElementGuid>926e9dab-d268-41c5-a84d-57bb3a45771b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'location_description_3298037' and @name = 'locations[3298037][description]']</value>
      <webElementGuid>67d7d514-9ea6-4b88-8e50-a4fd51fd04ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
