<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>a21b53a0-0ae3-4f7e-9d55-f6cee4c91f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'إضافة')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3807966-daa8-49d4-b177-c9124449cdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>804ff2fb-443a-4007-b3ab-f6e473028351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#imageModal</value>
      <webElementGuid>c1f34175-b780-46e9-8842-e432ffac7812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f53cc41d-39c9-4281-9dc9-1277477658bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>da22f702-a2f9-4fa0-bd7d-3974a5363678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إضافة</value>
      <webElementGuid>b80d89ab-268c-4db3-8aa7-de14dfab7883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;rtl horizontal-menu   breakpoint-1024 pace-done&quot;]/div[@class=&quot;page-container row-fluid&quot;]/div[@class=&quot;page-content m-0&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;content-section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;grid simple&quot;]/div[@class=&quot;grid-body&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;grid-body no-border&quot;]/div[@class=&quot;row control&quot;]/div[@class=&quot;col-sm-12 col-xs-12&quot;]/div[@class=&quot;pull-left markaction&quot;]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>c15824c6-6ac3-4d27-8d54-c3dd9fe2abf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'إضافة')]</value>
      <webElementGuid>6c3e73c7-ec9c-427f-b4ac-e409f4d093ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حذف'])[1]/following::a[1]</value>
      <webElementGuid>cc06ca25-3514-49ec-8f08-5775208fb92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المراجع'])[1]/following::a[2]</value>
      <webElementGuid>2059d55d-d904-41c7-ace6-688fad98cea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المرجع'])[1]/preceding::a[1]</value>
      <webElementGuid>f00084a9-9798-4429-ba69-18a7c78342d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المراجع المراجع المراجع ٢'])[1]/preceding::a[1]</value>
      <webElementGuid>c6ed86e1-9d0e-40a6-a7ce-b40b5857026c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة']/parent::*</value>
      <webElementGuid>26fd45ab-7d1f-4e56-bdf4-e3c456e82226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>4473060d-53c8-453c-b5fb-927574ecf11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>a1fd3d75-31bf-43ce-b2a7-b93af080b9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'إضافة' or . = 'إضافة')]</value>
      <webElementGuid>b431f8c0-b302-4c4c-b659-cad525aff37f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
