<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_superadmin_image-logo</name>
   <tag></tag>
   <elementGuidId>3cf03dc6-0615-4660-b52b-32569cb6b271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > img.image-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13a30315-a9f2-42b9-8d7e-764cee9f1707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-logo</value>
      <webElementGuid>5596e6a4-eae1-476e-a0b6-98b917eddcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png</value>
      <webElementGuid>f63e2ebc-a2f3-4913-b97d-1df8812806d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>badf47cf-9767-4a18-b911-4b8611f76335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;rtl horizontal-menu   breakpoint-1024 pace-done&quot;]/div[@class=&quot;header navbar navbar-inverse&quot;]/div[@class=&quot;navbar-inner&quot;]/div[@class=&quot;row logo&quot;]/div[@class=&quot;header-section&quot;]/div[@class=&quot;col-md-4 text-center&quot;]/a[1]/img[@class=&quot;image-logo&quot;]</value>
      <webElementGuid>4d387c5e-47d7-4ebb-8a91-c5af9cd388f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png')]</value>
      <webElementGuid>d0e972f0-ced3-40b0-a683-85d958a4981e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>9a090609-4ea4-4004-a5f4-a0e4d68840ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://testing.aljomaihfamilyapp.com/assets/img/logout-logo-new.png']</value>
      <webElementGuid>5e975968-8e67-44d7-b88a-c02b7ab22907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
