<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>1f151305-44b0-47a4-9cbc-33223f0bc8b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.classic.myClassic > li.classic > a > span.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bar-inner']/ul/li[3]/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>30bde3bb-02f3-41db-94c6-0d4bd2c91352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>e79c602d-aefc-4e49-bec8-e7884139c468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                النسب</value>
      <webElementGuid>1ce744c3-2364-42a8-aaba-39d152148bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bar-inner&quot;)/ul[@class=&quot;menus text-center&quot;]/li[@class=&quot;classic  open&quot;]/ul[@class=&quot;classic myClassic&quot;]/li[@class=&quot;classic&quot;]/a[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>6c01837d-1137-4d44-a443-0dbc68f55485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bar-inner']/ul/li[3]/ul/li/a/span</value>
      <webElementGuid>bbec72ca-7282-4d7d-be43-292ed80e0a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[2]</value>
      <webElementGuid>50d86a38-e359-4b0d-ab47-729b1a171447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المكتبة'])[1]/following::span[4]</value>
      <webElementGuid>baea2019-fe71-4489-9ab9-15d5def7b17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الدليل'])[1]/preceding::span[1]</value>
      <webElementGuid>e261d1de-7901-4679-b9ae-a4c05f7cd767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشجرة'])[1]/preceding::span[2]</value>
      <webElementGuid>fbfb4356-8f3e-4721-a3e0-f354a7c63e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='النسب']/parent::*</value>
      <webElementGuid>5a1d50f5-c75f-4462-b1a8-28b92234207c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/a/span</value>
      <webElementGuid>ef47797c-2462-4b12-b2e1-bc0965ba1afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                النسب' or . = '
                                النسب')]</value>
      <webElementGuid>7721e23a-37ce-43b3-b746-4a416714d6ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
