<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>49794846-48fa-4695-af43-1d93e61323fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Daleel&quot;] > span.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bar-inner']/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ca065c8f-a21f-4e96-b30f-64b127cffc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>fbd999c0-1f7d-4f67-b8d1-0401c6783318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>المكتبة</value>
      <webElementGuid>e3cd6e76-a4c6-4925-83bb-ed3739421eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bar-inner&quot;)/ul[@class=&quot;menus text-center&quot;]/li[@class=&quot;classic&quot;]/a[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>d2ddd7bb-fe08-493d-9d6b-ee8b99facd2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bar-inner']/ul/li[3]/a/span</value>
      <webElementGuid>fe97b923-54a3-4c01-878b-268a6035d87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='هام'])[1]/following::span[1]</value>
      <webElementGuid>76e06136-94b9-4e61-bf80-c66bf11e2241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التصويت'])[1]/following::span[2]</value>
      <webElementGuid>dac0ee45-868f-4af8-bf85-b187c2fbaa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[1]</value>
      <webElementGuid>97c7245c-e3f3-4bf0-b118-0aac79552def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='النسب'])[1]/preceding::span[4]</value>
      <webElementGuid>3f5eb32d-f798-4b42-a531-254d93b277a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='المكتبة']/parent::*</value>
      <webElementGuid>bacd102a-c28d-4ce7-8b11-292f78dfd816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>5d1b5e66-0440-4c9b-bb33-7450bcd02dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'المكتبة' or . = 'المكتبة')]</value>
      <webElementGuid>6ee22d10-0c44-4ffb-834b-d6cda03bd677</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
